name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the observed behavior.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior. Please provide as much detail as possible.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen when going through the steps?
      placeholder: Tell us what you expected to see!
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment.
      placeholder: |
        - Browser: (e.g., Chrome, Firefox, Safari)
        - OS: (e.g., macOS, Windows, Linux)
        - Device: (e.g., Desktop, Mobile)
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the bug report here.
    validations:
      required: false
